spring:
  application:
    name: hello-service

server:
  port: 8080

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://localhost:8761/eurka/

# feign 开启 hystrix
feign:
  hystrix:
    enabled: true

# 开启 hystrix 监控
management:
  security:
    enabled: false
  endpoints:
    web:
      exposure:
        include: hystrix.stream

# ribbon 超时时间设置（ms）
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 3000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0

# hystrix 超时时间设置（ms）
hystrix:
  command:
    default:
      execution:
        timeout:
          isolation:
            thread:
              timeoutInMilliseconds: 5000