server:
  port: 8099

spring:
  application:
    name: data-service

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# 开放 hystrix 监控端点
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream