spring:
  application:
    name: provider-service

server:
  port: 8081

eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      default-zone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

# -----------------------------------------------------------------------
# 开启 hystrix board
management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream

# feign 开启 hystrix
feign:
  hystrix:
    enabled: true

# ribbon 超时时间设置（ms）
ribbon:
  ConnectTimeout: 3000
  ReadTimeout: 3000
  MaxAutoRetries: 0
  MaxAutoRetriesNextServer: 0

# hystrix 超时时间设置（ms）
hystrix:
  command:
    default:
      execution:
        timeout:
          isolation:
            thread:
              timeoutInMilliseconds: 5000