server:
  port: 8012
spring:
  application:
    name: feign-upload-server

eureka:
  server:
    enable-self-preservation: false

  client:
    serviceUrl:
      defaultZone: http://${eureka.host:127.0.0.1}:${eureka.port:8761}/eureka/

  instance:
    prefer-ip-address: true