# --------------------------------------------------------------  服务屏蔽和路径屏蔽
spring:
  application:
    name: zuul-server

server:
  port: 5555

eureka:
  client:
    service-url:
      default-zone: http:/localhost:8761/eureka/
  instance:
    prefer-ip-address: true

zuul:
  # 服务 client-b 将被屏蔽掉
  ignored-services: client-b
  # 接口中带有 test 的将会被屏蔽掉
  ignored-patterns: /**/test/**
  prefix: /pre

  routes:
    client-a:
      path: /client/**
      serviceId: client-a
