spring:
  application:
    name: zuul-server

server:
  port: 5555

eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    fetch-registry: true
    register-with-eureka: true
  instance:
    prefer-ip-address: true

zuul:
  routes:
    provider:
      path: /provider/**
      serviceId: service-provider


# ----------------------------------------------------------------------  Oauth2 \u6388\u6743\u914D\u7F6E
security:
  basic:
    enabled: false
  oauth2:
    client:
      # \u83B7\u53D6\u4EE4\u724C\u7684\u7AEF\u70B9
      access-token-uri: http://localhost:7777/uaa/oauth/token
      # \u6388\u6743\u7AEF\u70B9
      user-authorization-uri: http://localhost:7777/uaa/oauth/authorize
      # Oauth2 \u5BA2\u6237\u7AEFID
      client-id: zuul_server
      # Oauth2 \u5BA2\u6237\u7AEF\u5BC6\u94A5
      client-secret: secret
    resource:
      jwt:
        # jwt \u5BC6\u94A5\uFF0C\u4F7F\u7528\u5BF9\u79F0\u52A0\u5BC6\uFF0C\u9ED8\u8BA4\u7B97\u6CD5\u4E3A HS256
        key-value: yuzh233
