server:
  port: 9090

spring:
  application:
    name: config-server

  cloud:
    config:
      server:
        git:
          uri: https://github.com/yuzh233/spring-cloud-learning-config-server.git
#          username:
#          password:
          search-paths: demo1
