server:
  port: 8000
spring:
  application:
    name: provider

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  # eureka.instance.prefer-ip-address  \u8868\u793A\u5C06\u81EA\u5DF1\u7684IP\u6CE8\u518C\u5230Eureka Server\u4E0A\uFF0C
  # \u5982\u679C\u4E0D\u914D\u7F6E,\u4F1A\u5C06\u5F53\u524D\u670D\u52A1\u63D0\u4F9B\u8005\u6240\u5728\u7684\u4E3B\u673A\u540D\u6CE8\u518C\u5230Eureka Server\u4E0A\u3002
  instance:
    prefer-ip-address: false